import './globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({ subsets: ['latin'], weight: ['200', '300', '400', '500', '700', '800'] })

export const metadata = {
  title: 'MyBills - Financial',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`h-screen flex flex-col justify-center items-center text-gray-500 ${poppins.className}`}>{children}</body>
    </html>
  )
}
