import './globals.css'
import { Poppins } from 'next/font/google'
import Navbar from './components/Navbar';

const poppins = Poppins({ subsets: ['latin'], weight: ['200', '300', '400', '500', '700', '800'] })

export const metadata = {
  title: 'MyBills - Financial',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
